version: "3.3"
services:
  aplicacion:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - 7000:80
    environment:
      - DB_IP=127.0.0.1
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=cultex
  aplicacion2:
    image: php:8.2-apache
    tty: true
    volumes:
      - ./:/var/www/html
    ports:
      - 7001:80
    environment:
      - DB_IP=127.0.0.1
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=cultex
  mysql:
    image: mysql:5.5
    tty: true
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=
    volumes:
      - ./mysql:/var/lib/mysql